- name: checking user exits
  hosts: localhost
  tasks: 
   - name: checking user
     ansible.builtin.command: id roboshop
     register: user
     ignore_errors: true
   - name: printing out put
     ansible.builtin.debug:
    # ignore-errors: true
      msg: "output is {{user}}"
   - name: printing ouput status
     ansible.builtin.debug:
      msg: "status of command is {{user.rc}}"

  
