- name: installing more packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing packages
      ansible.builtin.package:
       name: "{{item.name}}"
       state: "{{item.state}}"
      loop:
       - { name: 'git' , state: 'absent' }
       - { name: 'nginx' , state: 'absent' }
       - { name: 'nodejs' , state: 'present' }
       - { name: 'nginx' , state: 'absent' }

       
