- name: installing more packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing packages
      ansible.builtin.package:
       name: "{{item}}"
       state: present
      loop:
       - nginx
       - git
       - nodejs
    - name: checking sms"
      ansible.builtin.debug:
       msg: "package is installed {{item}}"

