- name: play var list
  hosts: localhost
  vars:
    person: "raghu"
    course: "daws"
    duration: "10hrs"
  tasks:
    - name: play var printing
      ansible.builtin.debug
       msg: "hai{{person}} iam learning {{course}} duration is {{duration}}"